/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/banner/Banner.vue')['default']
    BenefitList: typeof import('./src/components/business/BenefitList.vue')['default']
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    BusinessModel: typeof import('./src/components/business/BusinessModel.vue')['default']
    BusinessSectionContainer: typeof import('./src/components/business/BusinessSectionContainer.vue')['default']
    Button: typeof import('primevue/button')['default']
    EstimatedCost: typeof import('./src/components/business/EstimatedCost.vue')['default']
    ExpectedProfit: typeof import('./src/components/business/ExpectedProfit.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    FranchiseSteps: typeof import('./src/components/business/FranchiseSteps.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderNav: typeof import('./src/components/header/HeaderNav.vue')['default']
    HeaderSubNav: typeof import('./src/components/header/HeaderSubNav.vue')['default']
    HeaderTopBar: typeof import('./src/components/header/HeaderTopBar.vue')['default']
    ImageGallery: typeof import('./src/components/business/ImageGallery.vue')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductDetail: typeof import('./src/components/product/ProductDetail.vue')['default']
    ProductList: typeof import('./src/components/product/ProductList.vue')['default']
    ProductSectionContainer: typeof import('./src/components/product/ProductSectionContainer.vue')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/section/SectionTitle.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
