/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./components/dashboards/AdminMenu.vue')['default']
    AdminMenuItem: typeof import('./components/dashboards/AdminMenuItem.vue')['default']
    AdminSidebar: typeof import('./components/dashboards/AdminSidebar.vue')['default']
    AdminTopbar: typeof import('./components/dashboards/AdminTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    FloatingConfigurator: typeof import('./components/configurator/FloatingConfigurator.vue')['default']
    Footer: typeof import('./components/footer/Footer.vue')['default']
    FranchiseBenefit: typeof import('./components/franchise/presentation/FranchiseBenefit.vue')['default']
    FranchiseEstimatedCost: typeof import('./components/franchise/financials/FranchiseEstimatedCost.vue')['default']
    FranchiseExpectedProfit: typeof import('./components/franchise/financials/FranchiseExpectedProfit.vue')['default']
    FranchiseOnboarding: typeof import('./components/franchise/presentation/FranchiseOnboarding.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    HeaderNav: typeof import('./components/header/HeaderNav.vue')['default']
    HeaderTopBar: typeof import('./components/header/HeaderTopBar.vue')['default']
    LandingBanner: typeof import('./components/landing/LandingBanner.vue')['default']
    LandingFeaturedProducts: typeof import('./components/landing/LandingFeaturedProducts.vue')['default']
    LandingFranchise: typeof import('./components/landing/LandingFranchise.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    ProductCard: typeof import('./components/products/ProductCard.vue')['default']
    ProductCardLoading: typeof import('./components/products/ProductCardLoading.vue')['default']
    ProductFilters: typeof import('./components/products/ProductFilters.vue')['default']
    ProductList: typeof import('./components/products/ProductList.vue')['default']
    ProductOptions: typeof import('./components/products/ProductOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./components/common/SectionTitle.vue')['default']
    SectionWrapper: typeof import('./components/common/SectionWrapper.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    ThemeConfigurator: typeof import('./components/configurator/ThemeConfigurator.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
