name: Soli App Deployment to GitHub Pages

# Trigger the workflow on push to deploy-github branch or manual dispatch
on:
  push:
    branches:
      - deploy-github
  workflow_dispatch:

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Environment variables
env:
  NODE_VERSION: 22.9.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the Vue app
      - name: Build
        run: npm run build
        env:
          VUE_APP_BASE_URL: ${{ github.event.repository.name }}

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4